### ISSUE TITLE
GearSwap/refresh.lua:234: runtime error

### ISSUE THREAD

**Issue by ragnark78** [Byrth/Lua-Byrth#398] opened 2015-11-29 23:25 UTC
i'm getting the following error ...

Gearswap: Lua runtime error: GearSwap/refresh.lua:234: attempt to index field '?' (a nil value)

**Comment by Byrth** [comment] 2015-11-30 13:52
```player.race = res.races[player.race][language]```

What race are you / were you wearing a costume / etc.?

**Comment by Byrth** [comment] 2015-11-30 14:16
Thinking about it a bit more, this might also be caused by out of date resources. Here is a link to the current windower/res/races.lua : https://www.dropbox.com/s/02ov80fc6ljim15/races.lua?dl=0

**Comment by ragnark78** [comment] 2015-12-01 15:39
it was an issue with blinkmenot ... just came back to the game after a 9 month break so i was behind on reading up on the current glitches.


________________________________

**Comment by Byrth** [comment] 2015-12-01 16:48
Good to know. Going to close this issue then.

**Closed by Byrth** 2015-12-01 16:48 UTC
